"""
Entry point for the desktop application.

Launches the Qt event loop and applies the selected colour palette.
"""
import sys

from PySide6.QtCore import QCoreApplication
from PySide6.QtGui import QIcon, QPalette, QColor
from PySide6.QtWidgets import QApplication

from wavoscope.gui.colours import load_palette
from wavoscope.gui.main_window import MainWindow

# Qt resource bundle generated by pyrcc6 / rcc
import wavoscope.gui.resources_rc  # noqa: F401 – used at run-time


def main() -> None:
    """Create QApplication, apply theme, open main window and run."""
    QCoreApplication.setApplicationName("Wavoscope")
    app = QApplication(sys.argv)

    # Apply palette before any widget is shown
    palette_dict = load_palette("dark")
    qt_palette = QPalette()
    qt_palette.setColor(QPalette.Window, QColor(palette_dict["background"]))
    qt_palette.setColor(QPalette.WindowText, QColor(palette_dict["text"]))
    qt_palette.setColor(QPalette.Base, QColor(palette_dict["background"]))
    qt_palette.setColor(QPalette.AlternateBase, QColor(palette_dict["background"]))
    qt_palette.setColor(QPalette.Text, QColor(palette_dict["text"]))
    qt_palette.setColor(QPalette.Button, QColor(palette_dict["background"]))
    qt_palette.setColor(QPalette.ButtonText, QColor(palette_dict["text"]))
    app.setPalette(qt_palette)

    # Window icon (macOS & Windows pick it up from .desktop / .ico later)
    app.setWindowIcon(QIcon("./resources/icons/app-icon.svg"))

    window = MainWindow()
    window.show()
    sys.exit(app.exec())